### ISSUE TITLE
API Token error

### ISSUE THREAD

**Issue by swetha-sree** [justinshenk/deepemotion#3]
Using TensorFlow backend.
Traceback (most recent call last):
  File "app.py", line 41, in <module>
    os.environ['FULL_API_TOKEN'] = app.config.get('FULL_API_TOKEN') or os.environ['FULL_API_TOKEN']
  File "/home/user/anaconda3/envs/deepemotion/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'FULL_API_TOKEN'

Hi,
Can you please help me with API Token Generation

**Comment by justinshenk** [comment]
You can add the environment variable FULL_API_TOKEN in the line above with
os.putenv('FULL_API_TOKEN', '') as a workaround.
